project_id = "dlwafedtlvbvuoaopvsl"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.gemini-tts]
    verify_jwt = false
  [functions.orion-advogado-ai]
    verify_jwt = false
  [functions.orion-produtor-ai]
    verify_jwt = false
