import { useMemo, useCallback } from "react";
import { FileText, MapPin, User, Calendar, Scale, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { sanitizeHTML } from "@/lib/sanitize";

interface LegalDocumentSection {
  titulo: string;
  conteudo: string;
}

export interface LegalDocumentData {
  titulo: string;
  tipo: string;
  tribunal?: string;
  numeroProcesso?: string;
  relator?: string;
  dataJulgamento?: string;
  secoes: LegalDocumentSection[];
  fundamentacao: string;
  consequencias?: string;
  doutrina?: string;
  localData?: string;
  advogadoOAB?: string;
}

interface LegalDocumentPreviewProps {
  /** Raw HTML content from the pipeline */
  htmlContent?: string;
  /** Structured data (alternative to htmlContent) */
  data?: LegalDocumentData;
  className?: string;
  /** Callback to export the document as PDF */
  onExportPdf?: () => void;
  /** Callback to insert into the editor */
  onInsertToEditor?: () => void;
}

/**
 * Preview component for legal documents generated by the 9-agent pipeline.
 * Renders either raw HTML or structured data with proper legal formatting.
 */
export function LegalDocumentPreview({ htmlContent, data, className = "", onExportPdf, onInsertToEditor }: LegalDocumentPreviewProps) {
  const hasPlaceholders = useMemo(() => {
    if (htmlContent) return htmlContent.includes("[PREENCHER]");
    if (data) return JSON.stringify(data).includes("[PREENCHER]");
    return false;
  }, [htmlContent, data]);

  const actionButtons = (onExportPdf || onInsertToEditor) ? (
    <div className="legal-doc-actions">
      {onInsertToEditor && (
        <Button variant="outline" size="sm" className="text-xs gap-1.5" onClick={onInsertToEditor}>
          <FileText className="h-3.5 w-3.5" />
          Inserir no Editor
        </Button>
      )}
      {onExportPdf && (
        <Button size="sm" className="text-xs gap-1.5" onClick={onExportPdf}>
          <Download className="h-3.5 w-3.5" />
          Exportar PDF
        </Button>
      )}
    </div>
  ) : null;

  // If we have raw HTML from pipeline, render it with legal styling
  if (htmlContent) {
    return (
      <div className={`legal-document-preview ${className}`}>
        {actionButtons}
        <div
          className="legal-doc-content"
          dangerouslySetInnerHTML={{ __html: sanitizeHTML(htmlContent) }}
        />
        {hasPlaceholders && (
          <div className="legal-doc-placeholder-warning">
            ⚠ Este documento contém campos marcados com <code>[PREENCHER]</code> que precisam ser completados.
          </div>
        )}
        <style>{legalDocStyles}</style>
      </div>
    );
  }

  if (!data) {
    return (
      <div className={`flex items-center justify-center h-64 text-muted-foreground text-sm ${className}`}>
        <FileText className="h-5 w-5 mr-2 opacity-50" />
        Nenhum documento para visualizar
      </div>
    );
  }

  return (
    <div className={`legal-document-preview ${className}`}>
      {actionButtons}
      <div className="legal-doc-content">
        {/* Header */}
        <div className="legal-doc-header">
          <h1>{data.titulo}</h1>
          {data.tipo && (
            <p className="legal-doc-tipo">
              <Scale className="inline h-4 w-4 mr-1 opacity-60" />
              {data.tipo}
            </p>
          )}
        </div>

        {/* Metadata bar */}
        {(data.tribunal || data.numeroProcesso || data.relator || data.dataJulgamento) && (
          <div className="legal-doc-metadata">
            {data.tribunal && (
              <span className="legal-doc-meta-item">
                <strong>Tribunal:</strong> {data.tribunal}
              </span>
            )}
            {data.numeroProcesso && (
              <span className="legal-doc-meta-item">
                <strong>Nº Processo:</strong> {data.numeroProcesso}
              </span>
            )}
            {data.relator && (
              <span className="legal-doc-meta-item">
                <strong>Relator:</strong> {data.relator}
              </span>
            )}
            {data.dataJulgamento && (
              <span className="legal-doc-meta-item">
                <strong>Data:</strong> {data.dataJulgamento}
              </span>
            )}
          </div>
        )}

        {/* Sections */}
        {data.secoes.map((secao, index) => (
          <div key={index} className="legal-doc-secao">
            <h2>
              {toRoman(index + 1)}. {secao.titulo}
            </h2>
            <div dangerouslySetInnerHTML={{ __html: sanitizeHTML(secao.conteudo) }} />
          </div>
        ))}

        {/* Fundamentação */}
        {data.fundamentacao && (
          <div className="legal-doc-secao">
            <h2>Da Fundamentação Jurídica</h2>
            <div dangerouslySetInnerHTML={{ __html: sanitizeHTML(data.fundamentacao) }} />
          </div>
        )}

        {/* Consequências / Pedidos */}
        {data.consequencias && (
          <div className="legal-doc-secao">
            <h2>Dos Pedidos</h2>
            <div dangerouslySetInnerHTML={{ __html: sanitizeHTML(data.consequencias) }} />
          </div>
        )}

        {/* Doutrina */}
        {data.doutrina && (
          <div className="legal-doc-secao legal-doc-doutrina">
            <div dangerouslySetInnerHTML={{ __html: sanitizeHTML(data.doutrina) }} />
          </div>
        )}

        {/* Footer */}
        <div className="legal-doc-footer">
          <p className="legal-doc-local">
            <Calendar className="inline h-3.5 w-3.5 mr-1 opacity-50" />
            {data.localData || <span className="placeholder">[PREENCHER] Local e data</span>}
          </p>
          <div className="legal-doc-assinatura">
            <div className="legal-doc-linha-assinatura" />
            <p>
              <User className="inline h-3.5 w-3.5 mr-1 opacity-50" />
              {data.advogadoOAB || <span className="placeholder">[PREENCHER] Nome do Advogado — OAB/UF nº</span>}
            </p>
          </div>
        </div>

        {/* Placeholder warning */}
        {hasPlaceholders && (
          <div className="legal-doc-placeholder-warning">
            ⚠ Este documento contém campos marcados com <code>[PREENCHER]</code> que precisam ser completados.
          </div>
        )}
      </div>

      <style>{legalDocStyles}</style>
    </div>
  );
}

function toRoman(num: number): string {
  const romanNumerals: [number, string][] = [
    [10, "X"], [9, "IX"], [5, "V"], [4, "IV"], [1, "I"],
  ];
  let result = "";
  for (const [value, numeral] of romanNumerals) {
    while (num >= value) {
      result += numeral;
      num -= value;
    }
  }
  return result;
}

const legalDocStyles = `
.legal-document-preview {
  font-family: "Times New Roman", Georgia, serif;
  color: hsl(var(--foreground));
  max-width: 210mm;
  margin: 0 auto;
}

.legal-doc-content {
  padding: 3cm 2cm 2cm 3cm;
  background: hsl(var(--card));
  border: 1px solid hsl(var(--border));
  border-radius: 4px;
  line-height: 1.5;
  font-size: 12pt;
}

.legal-doc-header {
  text-align: center;
  margin-bottom: 2rem;
  padding-bottom: 1rem;
  border-bottom: 2px solid hsl(var(--border));
}

.legal-doc-header h1 {
  font-size: 16pt;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  margin: 0 0 0.5rem 0;
  color: hsl(var(--foreground));
}

.legal-doc-tipo {
  font-size: 11pt;
  color: hsl(var(--muted-foreground));
  margin: 0;
}

.legal-doc-metadata {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  padding: 0.75rem 1rem;
  margin-bottom: 1.5rem;
  background: hsl(var(--muted) / 0.3);
  border-radius: 4px;
  font-size: 10pt;
  color: hsl(var(--muted-foreground));
}

.legal-doc-meta-item strong {
  color: hsl(var(--foreground));
}

.legal-doc-secao {
  margin-bottom: 1.5rem;
}

.legal-doc-secao h2 {
  font-size: 13pt;
  font-weight: 700;
  text-transform: uppercase;
  margin: 0 0 0.75rem 0;
  color: hsl(var(--foreground));
}

.legal-doc-secao p {
  text-indent: 1.25cm;
  margin: 0 0 6pt 0;
  text-align: justify;
}

/* Jurisprudence citations — long quotes */
.legal-doc-content blockquote {
  margin: 1rem 0 1rem 4cm;
  padding: 0;
  font-size: 10pt;
  line-height: 1.2;
  border: none;
  color: hsl(var(--foreground));
}

.legal-doc-content blockquote strong {
  font-weight: 700;
}

.legal-doc-doutrina {
  font-size: 11pt;
  font-style: italic;
  border-left: 3px solid hsl(var(--primary));
  padding-left: 1rem;
  margin-left: 1rem;
}

.legal-doc-footer {
  margin-top: 3rem;
  text-align: center;
}

.legal-doc-local {
  font-size: 11pt;
  margin-bottom: 3rem;
  text-indent: 0 !important;
}

.legal-doc-assinatura {
  display: inline-block;
  text-align: center;
  min-width: 60%;
}

.legal-doc-linha-assinatura {
  border-top: 1px solid hsl(var(--foreground));
  margin-bottom: 0.5rem;
}

.legal-doc-assinatura p {
  font-size: 11pt;
  text-indent: 0 !important;
  margin: 0;
}

.placeholder {
  background: hsl(var(--accent));
  color: hsl(var(--accent-foreground));
  padding: 1px 6px;
  border-radius: 3px;
  font-size: 0.9em;
  font-weight: 500;
}

.legal-doc-placeholder-warning {
  margin-top: 2rem;
  padding: 0.75rem 1rem;
  background: hsl(var(--destructive) / 0.1);
  border: 1px solid hsl(var(--destructive) / 0.3);
  border-radius: 4px;
  font-size: 10pt;
  color: hsl(var(--destructive));
  text-align: center;
}

.legal-doc-placeholder-warning code {
  background: hsl(var(--muted));
  padding: 1px 4px;
  border-radius: 2px;
  font-size: 0.9em;
}

.legal-doc-actions {
  display: flex;
  justify-content: flex-end;
  gap: 0.5rem;
  padding: 0.75rem 1rem;
  border-bottom: 1px solid hsl(var(--border));
  background: hsl(var(--muted) / 0.2);
}
`;

export default LegalDocumentPreview;
