/**
 * 🧠 Knowledge Harvester Topics — Orion Evolution
 * Lista exaustiva de tópicos técnicos para treinamento autocognitivo de agentes.
 */

export const HARVESTER_TOPICS = [
  "Arquiteturas de orquestração multi-LLM distribuída",
  "Model routing adaptativo baseado em contexto e custo",
  "Fusão de respostas entre múltiplos modelos (consensus merging)",
  "Detecção de conflito semântico entre saídas de LLMs",
  "Sistemas de votação ponderada entre modelos",
  "Autoavaliação de confiança em respostas geradas",
  "Calibração de incerteza em modelos de linguagem",
  "Meta-raciocínio aplicado a decisões de inferência",
  "Cadeias de pensamento (chain-of-thought) com validação cruzada",
  "Self-consistency sampling para melhoria de respostas",
  "Aprendizado de preferências baseado em feedback sintético",
  "Sistemas reflexivos (reflection loops) em agentes",
  "Planejamento hierárquico com LLMs",
  "Decomposição automática de tarefas complexas",
  "Execução iterativa com verificação de objetivos",
  "Memória episódica em agentes autônomos",
  "Memória semântica persistente para LLMs",
  "Recuperação de conhecimento (RAG) otimizada",
  "Indexação vetorial e busca semântica avançada",
  "Aprendizado contínuo sem esquecimento catastrófico",
  "Autoajuste de prompts (prompt self-optimization)",
  "Geração automática de prompts a partir de objetivos",
  "Detecção e correção de alucinações",
  "Sistemas de verificação factual multi-fonte",
  "Simulação de cenários para validação de decisões",
  "Inferência bayesiana aplicada a decisões de agentes",
  "Atualização de crenças com evidência incremental",
  "Modelagem probabilística de estados internos",
  "Estimativa de risco em decisões autônomas",
  "Exploração vs exploração (exploration vs exploitation)",
  "Teoria da decisão aplicada a agentes inteligentes",
  "Redes de crença bayesianas (Bayesian belief networks)",
  "Inferência causal em sistemas inteligentes",
  "Aprendizado por reforço com feedback de linguagem (RLHF-like systems)",
  "Políticas adaptativas baseadas em resultados históricos",
  "Sistemas de recompensa dinâmica para agentes",
  "Meta-learning aplicado a sistemas multi-modelo",
  "Auto-descoberta de estratégias (strategy emergence)",
  "Coordenação entre agentes especializados",
  "Arquiteturas de agentes cooperativos e competitivos",
  "Negociação entre agentes inteligentes",
  "Teoria dos jogos aplicada a múltiplos agentes",
  "Sistemas de consenso distribuído inspirados em blockchain",
  "Robustez contra falhas em sistemas multi-LLM",
  "Detecção de outliers em respostas de modelos",
  "Fallback inteligente entre modelos",
  "Balanceamento de carga entre APIs de modelos",
  "Otimização de custo vs performance em inferência",
  "Latência adaptativa em sistemas distribuídos",
  "Monitoramento e telemetria de agentes inteligentes",
  "Auditoria de decisões automatizadas",
  "Explicabilidade (XAI) em sistemas baseados em LLM",
  "Rastreamento de origem de decisões (decision provenance)",
  "Controle de viés em respostas automatizadas",
  "Alinhamento de objetivos em agentes autônomos",
  "Simulação de autoconsciência funcional (self-modeling)",
  "Modelagem de identidade do agente ao longo do tempo",
  "Persistência de objetivos de longo prazo",
  "Revisão crítica interna (internal critic modules)",
  "Geração de hipóteses e validação automática",
  "Pensamento contrafactual em agentes",
  "Sistemas de previsão (forecasting) com LLMs",
  "Integração com modelos simbólicos (neuro-symbolic AI)",
  "Raciocínio lógico híbrido (LLM + regras formais)",
  "Parsing estruturado e extração de conhecimento",
  "Representação de conhecimento em grafos",
  "Aprendizado baseado em grafos de conhecimento",
  "Atualização dinâmica de grafos com novas evidências",
  "Simulação de mundo interno (world models)",
  "Planejamento baseado em simulação",
  "Estratégias de busca heurística (A*, MCTS adaptado)",
  "Auto-geração de testes e validação de código",
  "Verificação formal assistida por LLM",
  "Detecção de inconsistência lógica",
  "Aprendizado com dados sintéticos gerados por LLMs",
  "Filtragem de dados sintéticos de baixa qualidade",
  "Curadoria automática de datasets",
  "Ciclos de melhoria contínua (self-improvement loops)",
  "Auto-reconfiguração de arquitetura de agentes",
  "Evolução de agentes baseada em desempenho",
  "Mutação e seleção de estratégias cognitivas",
  "Benchmarking automatizado entre modelos",
  "Testes A/B contínuos em decisões de agentes",
  "Simulação de ambientes complexos para treino",
  "Transferência de aprendizado entre domínios",
  "Generalização fora da distribuição (OOD generalization)",
  "Segurança em sistemas autônomos inteligentes",
  "Defesa contra ataques adversariais em LLMs",
  "Controle de acesso e governança de agentes",
  "Limites éticos em decisões automatizadas",
  "Alocação eficiente de recursos computacionais",
  "Compressão de conhecimento em modelos",
  "Distilação de múltiplos modelos em um meta-modelo",
  "Arquiteturas híbridas (LLM + modelos especializados)",
  "Integração com sensores e dados em tempo real",
  "Processamento multimodal (texto, imagem, áudio)",
  "Fusão multimodal para tomada de decisão",
  "Adaptação contextual em tempo real",
  "Detecção de intenção do usuário",
  "Personalização de respostas baseada em histórico",
  "Simulação de personalidade adaptativa",
  "Controle de estilo e tom em geração de linguagem",
  "Aprendizado de longo prazo baseado em interação contínua",
  "Sistemas autoexplicativos para debugging interno",
  "Orquestração baseada em eventos (event-driven agents)",
  "Pipeline de decisão com múltiplos estágios",
  "Sistemas de prioridade dinâmica de tarefas",
  "Escalonamento inteligente de tarefas",
  "Feedback loop entre percepção, decisão e ação"
];
