/**
 * Vision Regional Description — Allows Orion to describe specific regions of an image.
 * Crops a region and generates a focused description using the existing VLM pipeline.
 */

import type { UnifiedDetection } from "./realtime-vision-engine";

export interface RegionOfInterest {
  /** Normalized coordinates [0,1] */
  x: number;
  y: number;
  width: number;
  height: number;
  /** Optional label for the region */
  label?: string;
}

export interface RegionalDescription {
  region: RegionOfInterest;
  /** Base64 cropped image data */
  croppedImageData: string;
  /** Description generated by VLM (filled externally) */
  description?: string;
  /** Objects found in this region */
  objectsInRegion: string[];
}

/**
 * Crop a region from a video element or canvas.
 */
export function cropRegion(
  source: HTMLVideoElement | HTMLCanvasElement,
  region: RegionOfInterest,
  outputSize: number = 256
): string | null {
  try {
    const canvas = document.createElement("canvas");
    canvas.width = outputSize;
    canvas.height = outputSize;
    const ctx = canvas.getContext("2d");
    if (!ctx) return null;

    const sw = source instanceof HTMLVideoElement ? source.videoWidth : source.width;
    const sh = source instanceof HTMLVideoElement ? source.videoHeight : source.height;

    const sx = Math.round(region.x * sw);
    const sy = Math.round(region.y * sh);
    const sWidth = Math.round(region.width * sw);
    const sHeight = Math.round(region.height * sh);

    ctx.drawImage(source, sx, sy, sWidth, sHeight, 0, 0, outputSize, outputSize);
    return canvas.toDataURL("image/jpeg", 0.8);
  } catch {
    return null;
  }
}

/**
 * Auto-detect interesting regions from detections.
 * Returns regions around detected objects that are worth describing in detail.
 */
export function detectInterestingRegions(
  detections: UnifiedDetection[],
  frameWidth: number,
  frameHeight: number,
  maxRegions: number = 3
): RegionOfInterest[] {
  if (detections.length === 0) return [];

  const regions: RegionOfInterest[] = [];

  // Priority: high-confidence detections that are NOT "person" (person is already described via face/pose)
  const interesting = detections
    .filter(d => d.confidence > 0.5)
    .sort((a, b) => {
      // Prioritize non-person objects and high confidence
      const aScore = (a.name === "person" ? 0.5 : 1) * a.confidence;
      const bScore = (b.name === "person" ? 0.5 : 1) * b.confidence;
      return bScore - aScore;
    })
    .slice(0, maxRegions);

  for (const det of interesting) {
    // Add padding around detection (20%)
    const pad = 0.2;
    const nx = Math.max(0, (det.x / frameWidth) - pad * (det.width / frameWidth));
    const ny = Math.max(0, (det.y / frameHeight) - pad * (det.height / frameHeight));
    const nw = Math.min(1 - nx, (det.width / frameWidth) * (1 + 2 * pad));
    const nh = Math.min(1 - ny, (det.height / frameHeight) * (1 + 2 * pad));

    regions.push({
      x: nx, y: ny, width: nw, height: nh,
      label: det.namePt
    });
  }

  return regions;
}

/**
 * Generate regional descriptions for a frame.
 * Returns cropped regions ready to be sent to VLM for description.
 */
export function prepareRegionalDescriptions(
  source: HTMLVideoElement | HTMLCanvasElement,
  detections: UnifiedDetection[],
  frameWidth: number,
  frameHeight: number
): RegionalDescription[] {
  const regions = detectInterestingRegions(detections, frameWidth, frameHeight);
  const descriptions: RegionalDescription[] = [];

  for (const region of regions) {
    const croppedImageData = cropRegion(source, region);
    if (!croppedImageData) continue;

    // Find which objects are in this region
    const objectsInRegion = detections
      .filter(d => {
        const dx = d.x / frameWidth;
        const dy = d.y / frameHeight;
        return dx >= region.x && dx <= region.x + region.width &&
               dy >= region.y && dy <= region.y + region.height;
      })
      .map(d => d.namePt);

    descriptions.push({
      region,
      croppedImageData,
      objectsInRegion
    });
  }

  return descriptions;
}

/**
 * Format regional descriptions for AI prompt.
 */
export function formatRegionalForAI(descriptions: RegionalDescription[]): string {
  if (descriptions.length === 0) return "";

  const parts = descriptions.map((d, i) => {
    const label = d.region.label ?? `Região ${i + 1}`;
    const objects = d.objectsInRegion.length > 0
      ? ` contendo: ${d.objectsInRegion.join(", ")}`
      : "";
    const desc = d.description ? ` — ${d.description}` : "";
    return `[${label}${objects}${desc}]`;
  });

  return `REGIÕES DE INTERESSE: ${parts.join(" | ")}`;
}
