// Zilliz raw-vector ops — for embeddings NOT generated by Gemini text (faces, voices).
// Accepts pre-computed vectors directly; routes to specialized collections.

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const ZILLIZ_ENDPOINT = Deno.env.get("ZILLIZ_ENDPOINT")!;
const ZILLIZ_TOKEN = Deno.env.get("ZILLIZ_TOKEN")!;

const COLLECTION_CONFIG: Record<string, { dim: number; metric: "COSINE" | "L2" | "IP" }> = {
  orion_faces: { dim: 512, metric: "L2" },
  orion_voices: { dim: 256, metric: "COSINE" },
  orion_legal: { dim: 768, metric: "COSINE" },
  orion_vision_memory: { dim: 256, metric: "COSINE" },
};

async function zilliz(path: string, body: unknown) {
  const res = await fetch(`${ZILLIZ_ENDPOINT}${path}`, {
    method: "POST",
    headers: {
      Accept: "application/json",
      Authorization: `Bearer ${ZILLIZ_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });
  const json = await res.json();
  if (!res.ok || (json.code && json.code !== 0 && json.code !== 200)) {
    throw new Error(`Zilliz error: ${JSON.stringify(json)}`);
  }
  return json;
}

async function ensureCollection(name: string) {
  const cfg = COLLECTION_CONFIG[name];
  if (!cfg) throw new Error(`Unknown collection: ${name}. Valid: ${Object.keys(COLLECTION_CONFIG).join(", ")}`);
  const list = await zilliz("/v2/vectordb/collections/list", {});
  if ((list.data ?? []).includes(name)) return;
  await zilliz("/v2/vectordb/collections/create", {
    collectionName: name,
    dimension: cfg.dim,
    metricType: cfg.metric,
    primaryFieldName: "id",
    idType: "VarChar",
    vectorFieldName: "vector",
    autoId: false,
    enableDynamicField: true,
    params: { max_length: 64 },
  });
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const { action = "search", collection, vector, vectors, items, topK = 5, filter, outputFields } =
      await req.json();

    if (!collection) {
      return new Response(JSON.stringify({ error: "collection required (orion_faces|orion_voices|orion_legal)" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    await ensureCollection(collection);
    const cfg = COLLECTION_CONFIG[collection];

    // ─── INSERT ──────────────────────────────────────────────────────
    if (action === "insert") {
      const list: { id: string; vector: number[]; metadata?: Record<string, unknown> }[] = items ?? [];
      if (!list.length) {
        return new Response(JSON.stringify({ error: "items array required" }), {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      // Validate dimensions
      for (const it of list) {
        if (!Array.isArray(it.vector) || it.vector.length !== cfg.dim) {
          return new Response(
            JSON.stringify({ error: `vector dim mismatch: expected ${cfg.dim}, got ${it.vector?.length}` }),
            { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
          );
        }
      }
      const data = list.map((it) => ({ id: it.id, vector: it.vector, ...(it.metadata ?? {}) }));
      const result = await zilliz("/v2/vectordb/entities/insert", { collectionName: collection, data });
      return new Response(JSON.stringify({ ok: true, inserted: data.length, result }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // ─── SEARCH ──────────────────────────────────────────────────────
    const q = vector ?? (Array.isArray(vectors) ? vectors[0] : null);
    if (!q || !Array.isArray(q)) {
      return new Response(JSON.stringify({ error: "vector (number[]) required for search" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (q.length !== cfg.dim) {
      return new Response(
        JSON.stringify({ error: `query vector dim mismatch: expected ${cfg.dim}, got ${q.length}` }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }
    const result = await zilliz("/v2/vectordb/entities/search", {
      collectionName: collection,
      data: [q],
      limit: topK,
      outputFields: outputFields ?? ["*"],
      ...(filter ? { filter } : {}),
    });
    return new Response(JSON.stringify({ ok: true, results: result.data ?? [] }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    return new Response(JSON.stringify({ error: (e as Error).message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
