#!/usr/bin/env node
/**
 * Generate public/sitemap.xml + public/robots.txt from src/lib/seo/public-routes.ts.
 *
 * Runs:
 *   - automatically on `vite build` (via vite-plugin in vite.config.ts)
 *   - manually with `node scripts/generate-sitemap.mjs`
 *
 * The script reads the routes file as text (no transpiler needed) and uses
 * tiny regex extraction so it works in pure Node without ts-node.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const ROUTES_FILE = resolve(ROOT, "src/lib/seo/public-routes.ts");
const PUBLIC_DIR = resolve(ROOT, "public");

function loadRoutes() {
  const src = readFileSync(ROUTES_FILE, "utf8");

  const baseMatch = src.match(/SITE_BASE_URL\s*=\s*"([^"]+)"/);
  const baseUrl = baseMatch ? baseMatch[1] : "https://www.iasofthub.com";

  const routes = [];
  const routeRegex =
    /\{\s*path:\s*"([^"]+)"\s*(?:,\s*priority:\s*([\d.]+))?\s*(?:,\s*changefreq:\s*"([^"]+)")?\s*\}/g;
  // Match only inside the publicRoutes array
  const arrayMatch = src.match(/publicRoutes[^=]*=\s*\[([\s\S]*?)\];/);
  const scope = arrayMatch ? arrayMatch[1] : src;
  let m;
  while ((m = routeRegex.exec(scope)) !== null) {
    routes.push({
      path: m[1],
      priority: m[2] ? Number(m[2]) : 0.5,
      changefreq: m[3] ?? "monthly",
    });
  }

  // Disallowed paths
  const disallow = [];
  const disallowMatch = src.match(/disallowedPaths[^=]*=\s*\[([\s\S]*?)\];/);
  if (disallowMatch) {
    const re = /"([^"]+)"/g;
    let dm;
    while ((dm = re.exec(disallowMatch[1])) !== null) {
      disallow.push(dm[1]);
    }
  }

  // Allowed bots
  const bots = [];
  const botsMatch = src.match(/allowedBots[^=]*=\s*\[([\s\S]*?)\];/);
  if (botsMatch) {
    const re = /"([^"]+)"/g;
    let bm;
    while ((bm = re.exec(botsMatch[1])) !== null) {
      bots.push(bm[1]);
    }
  }

  return { baseUrl, routes, disallow, bots };
}

function buildSitemap({ baseUrl, routes }) {
  const today = new Date().toISOString().slice(0, 10);
  const urls = routes
    .map(
      (r) => `  <url>
    <loc>${baseUrl}${r.path === "/" ? "/" : r.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority.toFixed(1)}</priority>
  </url>`,
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

function buildRobots({ baseUrl, disallow, bots }) {
  const allowBlocks = bots
    .map((b) => `User-agent: ${b}\nAllow: /\n`)
    .join("\n");
  const disallowLines = disallow.map((d) => `Disallow: ${d}`).join("\n");

  return `# Auto-generated by scripts/generate-sitemap.mjs — do not edit by hand.
${allowBlocks}
User-agent: *
Allow: /

${disallowLines}

Sitemap: ${baseUrl}/sitemap.xml
`;
}

function main() {
  const data = loadRoutes();
  if (data.routes.length === 0) {
    console.error("⚠️  No public routes parsed from", ROUTES_FILE);
    process.exit(1);
  }
  mkdirSync(PUBLIC_DIR, { recursive: true });
  writeFileSync(resolve(PUBLIC_DIR, "sitemap.xml"), buildSitemap(data));
  writeFileSync(resolve(PUBLIC_DIR, "robots.txt"), buildRobots(data));
  console.log(
    `✅ sitemap.xml (${data.routes.length} URLs) + robots.txt regenerated.`,
  );
}

main();
