
INSERT INTO publicacoes (titulo, resumo, conteudo, categoria, autor, slug, publicado, data_publicacao, user_id) VALUES
('ORION IA v3.0 — Nova Era da Inteligência Empresarial', 'Conheça as novidades da versão 3.0 do ORION IA com comandos de voz, visão computacional e multi-modelo neural.', '<h2>O Futuro Chegou</h2><p>A ELP Green Technology S.R.L. anuncia o lançamento oficial do <strong>ORION IA v3.0</strong>, a mais avançada plataforma de inteligência artificial empresarial do mercado.</p><h3>Principais Novidades</h3><ul><li><strong>Comandos de Voz:</strong> Ative o assistente simplesmente dizendo "Orion".</li><li><strong>Visão Computacional:</strong> OCR avançado e análise de documentos com a câmera.</li><li><strong>Multi-Modelo Neural:</strong> Orquestração inteligente entre Groq, Gemini, Mistral e Anthropic.</li></ul><p>Esta atualização representa um marco na automação empresarial.</p>', 'tecnologia', 'ELP Green Technology', 'orion-ia-v3-nova-era', true, now() - interval '2 days', '6699c758-cad4-4102-a606-eb68a333bbc6'),
('Compliance LGPD/GDPR — Como o ORION Protege Seus Dados', 'Entenda como a plataforma ORION garante total conformidade com as legislações de proteção de dados.', '<h2>Segurança em Primeiro Lugar</h2><p>A conformidade com a <strong>LGPD</strong> e o <strong>GDPR</strong> é prioridade absoluta no ORION.</p><ul><li><strong>Criptografia End-to-End</strong></li><li><strong>Anonimização Automática</strong></li><li><strong>Auditoria Completa</strong></li><li><strong>Direito ao Esquecimento</strong></li></ul>', 'compliance', 'ELP Green Technology', 'compliance-lgpd-gdpr-orion', true, now() - interval '5 days', '6699c758-cad4-4102-a606-eb68a333bbc6'),
('Automação Documental — Gere Contratos em Segundos', 'A IA do ORION automatiza LOIs, NDAs, contratos e documentos empresariais.', '<h2>Documentos Inteligentes</h2><p>O módulo de <strong>Automação Documental</strong> revoluciona a gestão de documentos.</p><ul><li><strong>LOI</strong> com dados pré-preenchidos</li><li><strong>NDA</strong> personalizados por jurisdição</li><li><strong>Contratos</strong> com cláusulas adaptativas</li><li><strong>Relatórios AML/KYC</strong> automatizados</li></ul>', 'ferramentas', 'ELP Green Technology', 'automacao-documental-contratos', true, now() - interval '8 days', '6699c758-cad4-4102-a606-eb68a333bbc6'),
('Rede Neural Distribuída — Conectando Escritórios Globalmente', 'Escritórios em diferentes países trabalham de forma integrada com a rede neural do ORION.', '<h2>Inteligência Conectada</h2><p>Sincronização em tempo real entre unidades de negócio globais.</p><ul><li><strong>Sincronização P2P</strong> via WebRTC</li><li><strong>Knowledge Base Compartilhada</strong></li><li><strong>Multi-Idioma:</strong> PT, EN, ES, IT, ZH</li><li><strong>Dashboard Unificado</strong></li></ul>', 'tecnologia', 'ELP Green Technology', 'rede-neural-distribuida-global', true, now() - interval '12 days', '6699c758-cad4-4102-a606-eb68a333bbc6'),
('Screening AML Internacional — Due Diligence Automatizada', 'Screening automático contra listas de sanções internacionais e PEPs em 200+ jurisdições.', '<h2>Due Diligence de Próximo Nível</h2><p>O módulo <strong>Screening AML</strong> automatiza a verificação anti-lavagem.</p><ul><li><strong>200+ Jurisdições</strong></li><li><strong>PEP Screening</strong></li><li><strong>Match Rate Configurável</strong></li><li><strong>Relatórios PDF</strong></li></ul>', 'compliance', 'ELP Green Technology', 'screening-aml-due-diligence', true, now() - interval '15 days', '6699c758-cad4-4102-a606-eb68a333bbc6'),
('Espaço de Trabalho para Advogados — Seu Escritório Digital', 'Advogados podem ter seu próprio site profissional integrado à plataforma ORION.', '<h2>Seu Escritório na Nuvem</h2><p>Espaço de trabalho digital completo para advogados.</p><ul><li><strong>Website Personalizado</strong></li><li><strong>Gestão de Clientes</strong> com CRM integrado</li><li><strong>Publicações</strong> e blog profissional</li><li><strong>Agendamento</strong> com pagamento via Stripe</li><li><strong>Ferramentas IA</strong> do ORION</li></ul>', 'servicos', 'ELP Green Technology', 'espaco-trabalho-advogados-digital', true, now() - interval '18 days', '6699c758-cad4-4102-a606-eb68a333bbc6');

INSERT INTO avaliacoes (nota, comentario, nome, depoimento, aprovado, user_id) VALUES
(5, 'Plataforma incrível! O ORION mudou completamente a forma como gerencio meu escritório.', 'Dr. Carlos Mendes', 'Desde que comecei a usar o ORION, minha produtividade triplicou. A automação documental e o assistente de voz são indispensáveis.', true, '6699c758-cad4-4102-a606-eb68a333bbc6'),
(5, 'A melhor ferramenta de compliance que já utilizei. Screening AML em segundos!', 'Dra. Ana Beatriz Costa', 'O módulo de screening AML é excepcional. Due diligence completa em minutos.', true, '6699c758-cad4-4102-a606-eb68a333bbc6'),
(4, 'Excelente suporte multilíngue. Uso diariamente em 3 idiomas.', 'Marco Rossetti', 'Como profissional entre Brasil e Itália, o suporte multilíngue é fundamental.', true, '6699c758-cad4-4102-a606-eb68a333bbc6'),
(5, 'A visão computacional do ORION é surpreendente!', 'Dra. Fernanda Lima', 'A funcionalidade de OCR com IA é fantástica. Digitalizo contratos instantaneamente.', true, '6699c758-cad4-4102-a606-eb68a333bbc6'),
(5, 'Revolucionário! Conectou nossos 4 escritórios perfeitamente.', 'Roberto Almeida', 'Temos escritórios em SP, Lisboa, Roma e Shenzhen. O ORION unificou tudo.', true, '6699c758-cad4-4102-a606-eb68a333bbc6'),
(4, 'Interface moderna e intuitiva. Geração de documentos por IA economiza horas.', 'Dra. Juliana Santos', 'As 8 camadas de revisão garantem precisão jurídica impecável.', true, '6699c758-cad4-4102-a606-eb68a333bbc6');
