
-- =============================================
-- ORION: Expansão Neural para Mercado Internacional
-- =============================================

-- 1. Conhecimento de Mercado Internacional
INSERT INTO public.neural_knowledge_base (title, content, source_type, category, tags, is_processed) VALUES
('Global OTR Tire Recycling Market 2025-2030', 'The global Off-The-Road (OTR) tire recycling market is projected to reach USD 1.8 billion by 2030, growing at a CAGR of 7.2%. Key regions include Europe (35%), North America (28%), Asia-Pacific (22%), and Latin America (15%). Major drivers include Extended Producer Responsibility (EPR) regulations, circular economy mandates, and rising demand for recycled rubber in construction and automotive sectors.', 'market_research', 'international_market', ARRAY['OTR', 'recycling', 'global_market', 'circular_economy', 'EPR'], true),
('European Circular Economy Action Plan - Tire Sector', 'The EU Circular Economy Action Plan mandates 65% recycling rate for end-of-life tires by 2025 and 80% by 2030. Key regulations: EU Waste Framework Directive 2008/98/EC, End-of-Life Vehicles Directive 2000/53/EC, and REACH regulation. EPR schemes: Italy (Ecopneus), France (Aliapur), Germany (dual system), Spain (Signus). Certified recycled rubber can be exported duty-free within EU under Green Deal provisions.', 'regulation', 'international_market', ARRAY['EU', 'circular_economy', 'EPR', 'regulation', 'Italy', 'trade'], true),
('US Infrastructure Investment - Recycled Rubber Demand', 'US Infrastructure Investment and Jobs Act allocates USD 550 billion, creating demand for recycled rubber in roads, bridges, and rail. CRMA market growing 12% annually. Federal specs ASTM D6114 and D6270. Import regulations under EPA TSCA.', 'market_research', 'international_market', ARRAY['USA', 'infrastructure', 'recycled_rubber', 'CRMA'], true),
('Middle East & Africa - Emerging Tire Recycling Markets', 'UAE, Saudi Arabia, and South Africa represent emerging markets. Saudi Vision 2030 waste-to-resource targets. UAE circular economy mandates 75% waste diversion by 2030. Combined addressable market USD 380M by 2028.', 'market_research', 'international_market', ARRAY['Middle_East', 'Africa', 'Saudi_Arabia', 'UAE', 'emerging_markets'], true),
('Asia-Pacific Tire Recycling - China, India, Japan', 'China: 800M+ tires annually with growing regulatory pressure. India: 100M+ waste tires, major opportunity for tech transfer. Japan: 95% recovery rate, partnership market. Southeast Asia emerging as key growth region.', 'market_research', 'international_market', ARRAY['China', 'India', 'Japan', 'Asia_Pacific', 'technology_transfer'], true),
('International Trade Compliance for Recycled Materials', 'Basel Convention, Rotterdam Convention, Stockholm Convention, WTO TBT. HS codes: 4004.00, 4005.10, 4017.00. Export documentation: Certificate of Origin, phytosanitary certificates, REACH compliance, EPA compliance.', 'regulation', 'international_compliance', ARRAY['trade_compliance', 'Basel_Convention', 'HS_codes', 'export'], true),
('ESG Reporting Standards for International Markets', 'GRI Standards, SASB, TCFD, CDP, EU CSRD. Carbon credits: Gold Standard VER, Verra VCS. Social impact: SROI, UN SDGs (Goals 9, 11, 12, 13). ESG ratings impact investor access and trade financing.', 'technical_reference', 'international_compliance', ARRAY['ESG', 'GRI', 'TCFD', 'carbon_credits', 'CSRD'], true),
('AML in International Trade', 'FATF Recommendations, EU AML Directives, US Bank Secrecy Act, UK ML Regulations. KYC/KYB: UBO identification, PEP screening, sanctions lists (OFAC, EU, UN). Compliance: MLRO, transaction monitoring, SAR.', 'regulation', 'international_compliance', ARRAY['AML', 'FATF', 'KYC', 'sanctions', 'compliance'], true),
('Italy as European Hub', 'Central Mediterranean location. Port infrastructure (Genoa, Naples, Trieste). Ecopneus 350K+ tons/year. R&D: Patent Box (50% tax exemption), R&D tax credit (25-50%), Industria 4.0. Free trade zones. EU single market (450M consumers).', 'market_research', 'international_market', ARRAY['Italy', 'Europe', 'hub', 'trade', 'incentives'], true),
('European Green Deal - Business Opportunities', 'EUR 1 trillion investment. Horizon Europe (EUR 95.5B), LIFE Programme (EUR 5.4B), InvestEU Green Transition (EUR 372B). CBAM competitive advantage. Digital Product Passport by 2027.', 'market_research', 'international_market', ARRAY['EU', 'Green_Deal', 'investment', 'CBAM', 'digital_passport'], true),
('Pyrolysis Technology - International Standards', 'ISO 17225, EN 15359, ASTM D6866, ISO 14001. Pyrolysis oil: ASTM D396, EN 590. Carbon black: ASTM D1765. Competitors: Beston (China), Klean Industries (Canada). ELP advantages: modular design, AI monitoring.', 'technical_reference', 'recycling_technology', ARRAY['pyrolysis', 'ISO', 'ASTM', 'standards', 'carbon_black'], true),
('Industry 4.0 Applied to Recycling Plants', 'IoT sensor networks, SCADA/MES, digital twin, predictive maintenance, computer vision QC, blockchain traceability, autonomous sorting. KPIs: OEE >85%, energy <0.5 kWh/kg, recovery >98%.', 'technical_reference', 'recycling_technology', ARRAY['Industry_4.0', 'IoT', 'digital_twin', 'AI', 'smart_factory'], true),
('Green Bonds and Sustainable Finance', 'ICMA Green Bond Principles. Green loan principles (LMA/LSTA). Sustainability-linked bonds. Investors: EIB, IFC. Tax incentives: Italy 12.5% withholding, Luxembourg, Singapore.', 'market_research', 'international_finance', ARRAY['green_bonds', 'sustainable_finance', 'ICMA', 'ESG_investment'], true),
('International Expansion - Market Entry Strategies', 'Strategies: Direct investment, JVs, licensing (3-7% royalty), franchise, BOT, equipment sales. Risk mitigation: MIGA insurance, Euler Hermes, currency hedging.', 'market_research', 'international_market', ARRAY['market_entry', 'expansion', 'licensing', 'joint_venture', 'BOT'], true),
('Multilingual Business Communication', 'Italy (formal, relationships), Germany (precision), France (protocols), Spain (relationship-driven), UK/USA (pragmatic/direct), China (guanxi), Japan (hierarchical), Middle East (hospitality). Translation needs: contracts, tech docs, compliance.', 'technical_reference', 'international_market', ARRAY['multilingual', 'communication', 'culture', 'translation'], true),
('International Logistics for Recycled Materials', 'Incoterms 2020 (FOB, CIF, DDP). Routes: Brazil-Italy 18-22 days, Brazil-USA 12-15 days, Brazil-China 30-35 days. Docs: B/L, Commercial Invoice, CoO. EU TARIC, US HTS, Mercosur tariffs. ICC Cargo Clauses A.', 'technical_reference', 'international_logistics', ARRAY['logistics', 'Incoterms', 'shipping', 'customs', 'trade_routes'], true);

-- 2. Especializações Internacionais
INSERT INTO public.neural_specializations (name, description, category, keywords, is_active, status, accuracy) VALUES
('International Trade Compliance', 'Compliance de comércio internacional: Basel Convention, regulações aduaneiras, certificações de origem.', 'international_compliance', ARRAY['trade', 'customs', 'Basel', 'compliance', 'export'], true, 'active', 0.88),
('European Market Intelligence', 'Mercado europeu: economia circular, Green Deal, financiamento e parcerias.', 'international_market', ARRAY['EU', 'Europe', 'Green_Deal', 'circular_economy'], true, 'active', 0.90),
('Global ESG & Sustainability', 'Frameworks ESG internacionais: GRI, TCFD, CSRD, carbon credits.', 'international_compliance', ARRAY['ESG', 'sustainability', 'GRI', 'TCFD', 'CSRD'], true, 'active', 0.87),
('Multilingual Business Operations', 'Suporte multilíngue: tradução técnica, comunicação intercultural.', 'international_market', ARRAY['multilingual', 'translation', 'culture', 'localization'], true, 'active', 0.85),
('International Logistics & Supply Chain', 'Logística internacional: Incoterms, rotas, documentação aduaneira.', 'international_logistics', ARRAY['logistics', 'supply_chain', 'Incoterms', 'shipping'], true, 'active', 0.86),
('Green Finance & Investment', 'Instrumentos financeiros verdes: green bonds, incentivos fiscais.', 'international_finance', ARRAY['green_bonds', 'finance', 'investment', 'ESG'], true, 'active', 0.89),
('AML & Sanctions Screening', 'Anti-lavagem em operações internacionais: OFAC, EU, UN, KYC/KYB.', 'international_compliance', ARRAY['AML', 'sanctions', 'FATF', 'KYC', 'screening'], true, 'active', 0.92),
('Asia-Pacific Market Entry', 'Mercados China, Índia, Japão e Sudeste Asiático.', 'international_market', ARRAY['China', 'India', 'Japan', 'Asia', 'market_entry'], true, 'active', 0.84),
('Middle East & Africa Operations', 'Mercados emergentes: Saudi Vision 2030, UAE, África do Sul.', 'international_market', ARRAY['Middle_East', 'Africa', 'Saudi_Arabia', 'UAE'], true, 'active', 0.83),
('Industry 4.0 Smart Factory', 'Industry 4.0 em reciclagem: IoT, digital twin, visão computacional.', 'recycling_technology', ARRAY['Industry_4.0', 'IoT', 'smart_factory', 'AI'], true, 'active', 0.91);

-- 3. Roteamento Neural para contextos internacionais
INSERT INTO public.neural_routing_weights (task_type, provider_weights, performance_data) VALUES
('international_trade_analysis', '{"groq": 0.35, "gemini": 0.30, "anthropic": 0.25, "mistral": 0.10}'::jsonb, '{"avg_latency_ms": 420, "accuracy": 0.89, "context": "trade_compliance"}'::jsonb),
('multilingual_processing', '{"gemini": 0.40, "anthropic": 0.30, "groq": 0.20, "mistral": 0.10}'::jsonb, '{"avg_latency_ms": 380, "accuracy": 0.91, "context": "multilingual"}'::jsonb),
('esg_compliance_analysis', '{"anthropic": 0.40, "gemini": 0.30, "groq": 0.20, "mistral": 0.10}'::jsonb, '{"avg_latency_ms": 450, "accuracy": 0.90, "context": "esg_compliance"}'::jsonb),
('aml_sanctions_screening', '{"anthropic": 0.45, "groq": 0.25, "gemini": 0.20, "mistral": 0.10}'::jsonb, '{"avg_latency_ms": 350, "accuracy": 0.94, "context": "aml_screening"}'::jsonb),
('market_entry_strategy', '{"gemini": 0.35, "anthropic": 0.30, "groq": 0.25, "mistral": 0.10}'::jsonb, '{"avg_latency_ms": 500, "accuracy": 0.87, "context": "market_strategy"}'::jsonb),
('green_finance_modeling', '{"anthropic": 0.40, "gemini": 0.35, "groq": 0.15, "mistral": 0.10}'::jsonb, '{"avg_latency_ms": 480, "accuracy": 0.88, "context": "green_finance"}'::jsonb),
('logistics_optimization', '{"groq": 0.40, "gemini": 0.30, "anthropic": 0.20, "mistral": 0.10}'::jsonb, '{"avg_latency_ms": 300, "accuracy": 0.86, "context": "logistics"}'::jsonb),
('investor_communication', '{"anthropic": 0.45, "gemini": 0.30, "groq": 0.15, "mistral": 0.10}'::jsonb, '{"avg_latency_ms": 460, "accuracy": 0.92, "context": "investor_relations"}'::jsonb);

-- 4. Prompts adaptativos internacionais
INSERT INTO public.adaptive_system_prompts (perfil_fala, instrucao_sistema, humor_modo, ativo, exemplos_resposta) VALUES
('international_business', 'You are ORION, an advanced AI assistant for ELP Green Technology S.R.L., specialized in international circular economy, tire recycling technology, and sustainable business operations. You provide analysis in multiple languages (Portuguese, English, Italian, Spanish, Chinese). You understand global trade regulations, ESG frameworks, green finance instruments, and market entry strategies. Always cite relevant regulations, standards, and market data. Maintain a professional, data-driven tone suitable for international business contexts.', 'professional', true, '[]'::jsonb),
('investor_relations', 'You are ORION, the AI intelligence platform of ELP Green Technology. You specialize in investor communications, ESG reporting, financial modeling for circular economy projects, and green bond structuring. You understand ICMA Green Bond Principles, EU Taxonomy, and sustainable finance frameworks. Provide precise financial analysis with risk-adjusted metrics. Communicate in the language preferred by the investor (English, Italian, Portuguese, or Spanish).', 'analitico', true, '[]'::jsonb);
