
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM auth.users WHERE id = 'f8028689-2e5c-4ae4-9e10-00562190f838') THEN
    INSERT INTO neural_knowledge_base (user_id, title, content, source_type, source_reference, tags, is_processed)
VALUES 
('f8028689-2e5c-4ae4-9e10-00562190f838', 'Inteligência Artificial - Definição, História e Aplicações (Atualizado)', 'Inteligência Artificial (IA) é a inteligência, raciocínio e aprendizado exibido por máquinas. Busca desenvolver máquinas autônomas capazes de simular o pensamento humano. Fundada como disciplina acadêmica em 1956, com pioneiros como Alan Turing, Herbert Simon e John McCarthy. Aplicações: mecanismos de busca (Google), sistemas de recomendação (YouTube, Amazon, Netflix), assistentes virtuais (Google Assistant, Siri, Alexa), veículos autônomos (Waymo), ferramentas generativas (ChatGPT, DeepSeek), OCR, tradução. Dois estilos: IA Simbólica (manipulação de símbolos e lógica) e IA Conexionista (redes neurais). Subcampos: ML, redes neurais profundas, NLP, visão computacional, robótica. Após 2012, deep learning superou técnicas anteriores. Modelos como GPT-3 e Transformers revolucionaram o campo.', 'wikipedia', 'https://pt.wikipedia.org/wiki/Inteligência_artificial#definicao-historia', ARRAY['inteligência artificial','machine learning','redes neurais','deep learning','NLP','transformers'], true),
('f8028689-2e5c-4ae4-9e10-00562190f838', 'Aprendizagem Mecânica e Memória de Trabalho para RAG', 'A aprendizagem mecânica (rote learning) é técnica de memorização baseada na repetição. Na computação, a máquina mantém histórico de cálculos e compara novas entradas: f(x1,...,xn) → (y1,...,yp) → armazenar. Usada pelo Game of Checkers de Arthur Samuel (IBM 701). A Memória de Trabalho (Working Memory) é sistema cognitivo ativo que mantém e manipula informações temporárias para tarefas atuais. Em RAG, implementa-se como cache de contexto com TTL curto. Diferencia-se da memória episódica (médio prazo) e memória de longo prazo (consolidação cortical). Alternativas: aprendizagem significativa, associativa, repetição espaçada, aprendizagem ativa.', 'wikipedia', 'https://pt.wikipedia.org/wiki/Aprendizagem_mecânica', ARRAY['aprendizagem mecânica','rote learning','working memory','memória de trabalho','cache','RAG'], true),
('f8028689-2e5c-4ae4-9e10-00562190f838', 'Tipos de IA (ANI, AGI, ASI) e Debates Filosóficos', 'Tipos de IA: 1) ANI (Artificial Narrow Intelligence) - IA Fraca, tarefas específicas. 2) AGI (Artificial General Intelligence) - IA Forte, qualquer tarefa humana. 3) ASI (Artificial Super Intelligence) - superaria inteligência humana. Debates: John Searle e Quarto Chinês (manipulação de símbolos não é compreensão). Hubert Dreyfus criticou IA simbólica. Daniel Dennett defende consciência emergente de processos computacionais. Marvin Minsky: Sociedade da Mente (inteligência emerge de agentes simples). Riscos: impacto no emprego, concentração tecnológica, vieses algorítmicos, privacidade.', 'wikipedia', 'https://pt.wikipedia.org/wiki/Inteligência_artificial#tipos-debates', ARRAY['ANI','AGI','ASI','filosofia da IA','ética','riscos'], true),
('f8028689-2e5c-4ae4-9e10-00562190f838', 'Subcampos e Técnicas de IA - ML, NLP, Visão Computacional, RLHF', 'Subcampos: 1) ML: supervisionado, não-supervisionado, por reforço. 2) Redes Neurais: modelo inspirado no cérebro. 3) NLP: compreensão e geração de linguagem. 4) Visão Computacional. 5) Robótica Autônoma. 6) Processamento de Áudio/Voz. 7) IA Generativa. Técnicas: Transformers (atenção multi-cabeça), Deep Learning, CNN, RNN/LSTM, GANs, RLHF (Reinforcement Learning from Human Feedback), RAG (Retrieval-Augmented Generation). Conceitos: embeddings vetoriais, tokenização, fine-tuning, transfer learning, few-shot learning, chain-of-thought reasoning.', 'wikipedia', 'https://pt.wikipedia.org/wiki/Inteligência_artificial#subcampos-tecnicas', ARRAY['ML','NLP','visão computacional','deep learning','transformers','RLHF','RAG','embeddings'], true);
  END IF;
END $$;
