CREATE TABLE IF NOT EXISTS public.orion_memory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  memory_key TEXT NOT NULL,
  memory_type TEXT DEFAULT 'preference',
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, memory_key)
);

ALTER TABLE public.orion_memory ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own memories"
  ON public.orion_memory FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own memories"
  ON public.orion_memory FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own memories"
  ON public.orion_memory FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own memories"
  ON public.orion_memory FOR DELETE
  USING (auth.uid() = user_id);

CREATE TRIGGER update_orion_memory_updated_at
  BEFORE UPDATE ON public.orion_memory
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();